/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as EsportsIndexRouteImport } from './routes/esports.index'
import { Route as ReferenceNewsRouteImport } from './routes/reference.news'
import { Route as ReferenceGamesRouteImport } from './routes/reference.games'
import { Route as ReferenceEsportsRouteImport } from './routes/reference.esports'
import { Route as NewsSlugRouteImport } from './routes/news_.$slug'
import { Route as GamesSlugRouteImport } from './routes/games_.$slug'
import { Route as EsportsMatchIdRouteImport } from './routes/esports_.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsIndexRoute = EsportsIndexRouteImport.update({
  id: '/esports/',
  path: '/esports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceNewsRoute = ReferenceNewsRouteImport.update({
  id: '/reference/news',
  path: '/reference/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceGamesRoute = ReferenceGamesRouteImport.update({
  id: '/reference/games',
  path: '/reference/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceEsportsRoute = ReferenceEsportsRouteImport.update({
  id: '/reference/esports',
  path: '/reference/esports',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games_/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsMatchIdRoute = EsportsMatchIdRouteImport.update({
  id: '/esports_/$matchId',
  path: '/esports/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esports/$matchId': typeof EsportsMatchIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/reference/esports': typeof ReferenceEsportsRoute
  '/reference/games': typeof ReferenceGamesRoute
  '/reference/news': typeof ReferenceNewsRoute
  '/esports/': typeof EsportsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esports/$matchId': typeof EsportsMatchIdRoute
  '/games/$slug': typeof GamesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/reference/esports': typeof ReferenceEsportsRoute
  '/reference/games': typeof ReferenceGamesRoute
  '/reference/news': typeof ReferenceNewsRoute
  '/esports': typeof EsportsIndexRoute
  '/games': typeof GamesIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/esports_/$matchId': typeof EsportsMatchIdRoute
  '/games_/$slug': typeof GamesSlugRoute
  '/news_/$slug': typeof NewsSlugRoute
  '/reference/esports': typeof ReferenceEsportsRoute
  '/reference/games': typeof ReferenceGamesRoute
  '/reference/news': typeof ReferenceNewsRoute
  '/esports/': typeof EsportsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esports/$matchId'
    | '/games/$slug'
    | '/news/$slug'
    | '/reference/esports'
    | '/reference/games'
    | '/reference/news'
    | '/esports/'
    | '/games/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esports/$matchId'
    | '/games/$slug'
    | '/news/$slug'
    | '/reference/esports'
    | '/reference/games'
    | '/reference/news'
    | '/esports'
    | '/games'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/esports_/$matchId'
    | '/games_/$slug'
    | '/news_/$slug'
    | '/reference/esports'
    | '/reference/games'
    | '/reference/news'
    | '/esports/'
    | '/games/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EsportsMatchIdRoute: typeof EsportsMatchIdRoute
  GamesSlugRoute: typeof GamesSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ReferenceEsportsRoute: typeof ReferenceEsportsRoute
  ReferenceGamesRoute: typeof ReferenceGamesRoute
  ReferenceNewsRoute: typeof ReferenceNewsRoute
  EsportsIndexRoute: typeof EsportsIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports/': {
      id: '/esports/'
      path: '/esports'
      fullPath: '/esports/'
      preLoaderRoute: typeof EsportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/news': {
      id: '/reference/news'
      path: '/reference/news'
      fullPath: '/reference/news'
      preLoaderRoute: typeof ReferenceNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/games': {
      id: '/reference/games'
      path: '/reference/games'
      fullPath: '/reference/games'
      preLoaderRoute: typeof ReferenceGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/esports': {
      id: '/reference/esports'
      path: '/reference/esports'
      fullPath: '/reference/esports'
      preLoaderRoute: typeof ReferenceEsportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$slug': {
      id: '/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/$slug': {
      id: '/games_/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports_/$matchId': {
      id: '/esports_/$matchId'
      path: '/esports/$matchId'
      fullPath: '/esports/$matchId'
      preLoaderRoute: typeof EsportsMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EsportsMatchIdRoute: EsportsMatchIdRoute,
  GamesSlugRoute: GamesSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ReferenceEsportsRoute: ReferenceEsportsRoute,
  ReferenceGamesRoute: ReferenceGamesRoute,
  ReferenceNewsRoute: ReferenceNewsRoute,
  EsportsIndexRoute: EsportsIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
